CREATE TABLE IF NOT EXISTS USERS (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50),
    password VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS STUDENT (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50),
    marks INTEGER
);